name: Deploy to Azure Container Instances
on:
  push:
    branches:
      - azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . --build-arg AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --build-arg AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
            --build-arg AWS_DATABASE_HOST="${{secrets.AWS_DATABASE_HOST}}" \
            --build-arg AWS_DATABASE_USERNAME="${{secrets.AWS_DATABASE_USERNAME}}"\
            --build-arg AWS_DATABASE_PASSWORD="${{secrets.AWS_DATABASE_PASSWORD}}"\
            --build-arg AWS_DATABASE_NAME="${{secrets.AWS_DATABASE_NAME}}" \
            --build-arg AWS_DATABASE_TABLE="${{secrets.AWS_DATABASE_TABLE}}"\
            --build-arg AWS_BUCKET_NAME="${{secrets.AWS_BUCKET_NAME}}" \
            --build-arg AWS_BUCKET_HEADER_URL="${{secrets.AWS_BUCKET_HEADER_URL}}"
            -t ${{secrets.REGISTRY_LOGIN_SERVER}}/pressureapp:${{github.sha}}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/pressureapp:${{ github.sha }}

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/pressureapp:${{ github.sha }}
          cpu: 2
          memory: 4
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-searchdataapp
          location: "west us"
          ports: 8080